---
- name: "ensure directory for global nginx configuration files exists"
  file:
    path: /etc/nginx/global.d
    state: directory
  become: yes

- name: "ensure phpmyadmin configuration for nginx is installed"
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/global.d/phpmyadmin.conf
  become: yes
  notify: "restart web server"
